prepend(
  RUNTIME_STDLIB_SRC
  stdlib/
  component/component-api.cpp
  exit/exit-functions.cpp
  fork/fork-context.cpp
  output/output-buffer.cpp
  output/print-functions.cpp
  rpc/rpc-api.cpp
  rpc/rpc-context.cpp
  rpc/rpc-extra-headers.cpp
  rpc/rpc-extra-info.cpp
  rpc/rpc-tl-error.cpp
  rpc/rpc-tl-query.cpp
  rpc/rpc-tl-request.cpp
  string/concat.cpp)
