prepend(
  RUNTIME_STDLIB_SRC
  stdlib/
  string-functions.cpp
  variable-handling.cpp
  component/component-api.cpp
  exit/exit.cpp
  fork/fork-api.cpp
  fork/fork-context.cpp
  output/output-buffer.cpp
  rpc/rpc-api.cpp
  rpc/rpc-context.cpp
  rpc/rpc-extra-headers.cpp
  rpc/rpc-extra-info.cpp
  rpc/rpc-tl-error.cpp
  rpc/rpc-tl-query.cpp
  rpc/rpc-tl-request.cpp)
