<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

#ifndef KPHP

namespace VK\TL;

/**
 * @kphp-tl-class
 */
interface RpcFunction {

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName();
}

/**
 * @kphp-tl-class
 */
interface RpcFunctionReturnResult {

}

#endif
