<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

#ifndef KPHP

namespace VK\TL;

interface RpcFunctionFetcher {

  /**
   * @param \VK\TL\RpcFunctionReturnResult $result
   */
  public function typedStore($result);
  /**
   * @return \VK\TL\RpcFunctionReturnResult
   */
  public function typedFetch();
}

#endif
