<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

#ifndef KPHP

namespace VK\TL;

use VK\TL;

/**
 * @kphp-tl-class
 */
interface RpcResponse {

  /** Allows kphp implicitly load all available constructors */
  const CONSTRUCTORS = [
    TL\_common\Types\rpcResponseError::class,
    TL\_common\Types\rpcResponseHeader::class,
    TL\_common\Types\rpcResponseOk::class
  ];

  /**
   * @return TL\RpcFunctionReturnResult
   */
  public function getResult();

  /**
   * @return TL\_common\Types\rpcResponseHeader
   */
  public function getHeader();

  /**
   * @return bool
   */
  public function isError();

  /**
   * @return TL\_common\Types\rpcResponseError
   */
  public function getError();

}

#endif
