<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\net\Types;

/**
 * @kphp-tl-class
 */
class net_pid {

  /** @var int */
  public $ip = 0;

  /** @var int */
  public $port_pid = 0;

  /** @var int */
  public $utime = 0;

  /**
   * @param int $ip
   * @param int $port_pid
   * @param int $utime
   */
  public function __construct($ip = 0, $port_pid = 0, $utime = 0) {
    $this->ip = $ip;
    $this->port_pid = $port_pid;
    $this->utime = $utime;
  }

}
