import json
import csv
import argparse
import pathlib
import collections

SCRIPT_DIR = pathlib.Path(__file__).parent
DEFAULT_OUTPUT = SCRIPT_DIR / 'tmp' / 'std_function_invocations.csv'

def main():
    parser = argparse.ArgumentParser(
        description="Aggregates std function invocations from multiple JSON files into a single CSV report."
    )

    parser.add_argument(
        'inputs',
        nargs='+',
        type=pathlib.Path,
        help='Paths to the JSON files generated by test groups',
    )

    parser.add_argument(
        '--output', '-o',
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help=f'Path to the output CSV file (default: {DEFAULT_OUTPUT})',
    )
    
    args = parser.parse_args()
    total_counts = collections.defaultdict(int)

    for file_path in args.inputs:
        if file_path.exists():
            try:
                data = json.loads(file_path.read_text(encoding='utf-8'))
                if isinstance(data, dict):
                    for func_name, count in data.items():
                        total_counts[func_name] += count
                else:
                    print(f"Warning: {file_path} content is not a dictionary. Skipping.")
            except json.JSONDecodeError:
                print(f"Error: {file_path} is not a valid JSON file. Skipping.")
        else:
            print(f"Info: {file_path} not found. It might have been disabled.")

    args.output.parent.mkdir(parents=True, exist_ok=True)

    try:
        with args.output.open('w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Built-in', 'Call count'])

            sorted_results = sorted(total_counts.items(), key=lambda item: (item[1], item[0]))

            for func, count in sorted_results:
                writer.writerow([func, count])
        
        print(f"Success! Aggregated report saved to: {args.output.absolute()}")
    except Exception as e:
        print(f"Error saving report: {e}")

if __name__ == "__main__":
    main()
