<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\tracing\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
class tracing_traceContext {

  /** Field mask for $parent_id field */
  const BIT_PARENT_ID_2 = (1 << 2);

  /** Field mask for $source_id field */
  const BIT_SOURCE_ID_3 = (1 << 3);

  /** Field mask for $reserved_status_0 field */
  const BIT_RESERVED_STATUS_0_0 = (1 << 0);

  /** Field mask for $reserved_status_1 field */
  const BIT_RESERVED_STATUS_1_1 = (1 << 1);

  /** Field mask for $reserved_level_0 field */
  const BIT_RESERVED_LEVEL_0_4 = (1 << 4);

  /** Field mask for $reserved_level_1 field */
  const BIT_RESERVED_LEVEL_1_5 = (1 << 5);

  /** Field mask for $reserved_level_2 field */
  const BIT_RESERVED_LEVEL_2_6 = (1 << 6);

  /** Field mask for $debug_flag field */
  const BIT_DEBUG_FLAG_7 = (1 << 7);

  /** @var int */
  public $fields_mask = 0;

  /** @var TL\tracing\Types\tracing_traceID */
  public $trace_id = null;

  /** @var int|null */
  public $parent_id = null;

  /** @var string|null */
  public $source_id = null;

  /** @var boolean */
  public $reserved_status_0 = false;

  /** @var boolean */
  public $reserved_status_1 = false;

  /** @var boolean */
  public $reserved_level_0 = false;

  /** @var boolean */
  public $reserved_level_1 = false;

  /** @var boolean */
  public $reserved_level_2 = false;

  /** @var boolean */
  public $debug_flag = false;

  /**
   * @param int $fields_mask
   * @param TL\tracing\Types\tracing_traceID $trace_id
   */
  public function __construct($fields_mask = 0, $trace_id = null) {
    $this->fields_mask = $fields_mask;
    $this->trace_id = $trace_id;
  }

  /**
   * @return int
   */
  public function calculateFieldsMask() {
    $mask = 0;

    if ($this->reserved_status_0) {
      $mask |= self::BIT_RESERVED_STATUS_0_0;
    }

    if ($this->reserved_status_1) {
      $mask |= self::BIT_RESERVED_STATUS_1_1;
    }

    if ($this->parent_id !== null) {
      $mask |= self::BIT_PARENT_ID_2;
    }

    if ($this->source_id !== null) {
      $mask |= self::BIT_SOURCE_ID_3;
    }

    if ($this->reserved_level_0) {
      $mask |= self::BIT_RESERVED_LEVEL_0_4;
    }

    if ($this->reserved_level_1) {
      $mask |= self::BIT_RESERVED_LEVEL_1_5;
    }

    if ($this->reserved_level_2) {
      $mask |= self::BIT_RESERVED_LEVEL_2_6;
    }

    if ($this->debug_flag) {
      $mask |= self::BIT_DEBUG_FLAG_7;
    }

    return $mask;
  }

}
