// Compiler for PHP (aka KPHP)
// Copyright (c) 2020 LLC «V Kontakte»
// Distributed under the GPL v3 License, see LICENSE.notice.txt

#pragma once

#include <cstddef>

/// It binds generated code and runtime. Definition is generated by compiler. This function is called at global initialization @see init_all().
void init_php_scripts() noexcept;
/// It initializes const variables. Definition is generated by compiler. This function is called at global initialization @see init_all().
void global_init_php_scripts() noexcept;
