// Compiler for PHP (aka KPHP)
// Copyright (c) 2020 LLC «V Kontakte»
// Distributed under the GPL v3 License, see LICENSE.notice.txt

/* Autogenerated from engine.tl and left only used constants */
#pragma once

#define TL_ENGINE_COUNT 0x19d0f020U
#define TL_ENGINE_FILTERED_STAT 0x594870d6U
#define TL_ENGINE_MC_ADD_QUERY 0xd02f7d07U
#define TL_ENGINE_MC_DECR_QUERY 0x71f416e9U
#define TL_ENGINE_MC_DELETE_QUERY 0x828688dcU
#define TL_ENGINE_MC_GET_QUERY 0x62408e9eU
#define TL_ENGINE_MC_INCR_QUERY 0xcadd63e1U
#define TL_ENGINE_MC_REPLACE_QUERY 0x5dc86a99U
#define TL_ENGINE_MC_SET_QUERY 0x3bd91922U
#define TL_ENGINE_NOP 0x166bb7c6U
#define TL_ENGINE_PID 0x559d6e36U
#define TL_ENGINE_READ_NOP 0x9d2b841fU
#define TL_ENGINE_SEND_SIGNAL 0x1a7708a3U
#define TL_ENGINE_SET_VERBOSITY 0x9d980926U
#define TL_ENGINE_SET_VERBOSITY_TYPE 0x5388c0aeU
#define TL_ENGINE_SLEEP 0x3d3bcd48U
#define TL_ENGINE_STAT 0xefb3c36bU
#define TL_ENGINE_VERSION 0x1a2e06faU
#define TL_ENGINE_WRITE_NOP 0x58160af4U
