// Compiler for PHP (aka KPHP)
// Copyright (c) 2020 LLC «V Kontakte»
// Distributed under the GPL v3 License, see LICENSE.notice.txt

/* Autogenerated from net.tl and left only used constants */
#pragma once

#define TL_NET_PID 0x46409ccfU
