<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\engine\Functions;

use VK\TL;

/**
 * @kphp-tl-class
 */
class engine_readNop implements TL\RpcFunction {

  /** Allows kphp implicitly load function result class */
  private const RESULT = TL\engine\Functions\engine_readNop_result::class;

  /**
   * @kphp-inline
   */
  public function __construct() {
  }

  /**
   * @param TL\RpcFunctionReturnResult $function_return_result
   * @return boolean
   */
  public static function functionReturnValue($function_return_result) {
    if ($function_return_result instanceof engine_readNop_result) {
      return $function_return_result->value;
    }
    warning('Unexpected result type in functionReturnValue: ' . ($function_return_result ? get_class($function_return_result) : 'null'));
    return (new engine_readNop_result())->value;
  }

  /**
   * @kphp-inline
   *
   * @param TL\RpcResponse $response
   * @return boolean
   */
  public static function result(TL\RpcResponse $response) {
    return self::functionReturnValue($response->getResult());
  }

  /**
   * @kphp-inline
   *
   * @return int
   */
  public function getTLFunctionMagic() {
    return 0x9d2b841f;
  }

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName() {
    return 'engine.readNop';
  }

  /**
   * @kphp-inline
   *
   * @return TL\RpcFunctionFetcher
   */
  public function typedStore(){
    return null;
  }

  /**
   * @kphp-inline
   *
   * @return TL\RpcFunctionFetcher
   */
  public function typedFetch(){
    return null;
  }

}

/**
 * @kphp-tl-class
 */
class engine_readNop_result implements TL\RpcFunctionReturnResult {

  /** @var boolean */
  public $value = true;

}
