<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\engine\Functions;

use VK\TL;

/**
 * @kphp-tl-class
 */
class engine_pid implements TL\RpcFunction {

  /** Allows kphp implicitly load function result class */
  private const RESULT = TL\engine\Functions\engine_pid_result::class;

  /**
   * @kphp-inline
   */
  public function __construct() {
  }

  /**
   * @param TL\RpcFunctionReturnResult $function_return_result
   * @return TL\net\Types\net_pid
   */
  public static function functionReturnValue($function_return_result) {
    if ($function_return_result instanceof engine_pid_result) {
      return $function_return_result->value;
    }
    warning('Unexpected result type in functionReturnValue: ' . ($function_return_result ? get_class($function_return_result) : 'null'));
    return (new engine_pid_result())->value;
  }

  /**
   * @kphp-inline
   *
   * @param TL\RpcResponse $response
   * @return TL\net\Types\net_pid
   */
  public static function result(TL\RpcResponse $response) {
    return self::functionReturnValue($response->getResult());
  }

  /**
   * @kphp-inline
   *
   * @return \RpcFunctionFetcher
   */
  public function customStore(){
    return null;
  }

  /**
   * @kphp-inline
   *
   * @return \RpcFunctionFetcher
   */
  public function customFetch(){
    return null;
  }

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName() {
    return 'engine.pid';
  }

}

/**
 * @kphp-tl-class
 */
class engine_pid_result implements TL\RpcFunctionReturnResult {

  /** @var TL\net\Types\net_pid */
  public $value = null;

}
