<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\engine\Functions;

use VK\TL;

/**
 * @kphp-tl-class
 */
class engine_sleep implements TL\RpcFunction {

  /** @var int */
  public $time_ms = 0;

  /** Allows kphp implicitly load function result class */
  private const RESULT = TL\engine\Functions\engine_sleep_result::class;

  /**
   * @param int $time_ms
   */
  public function __construct($time_ms = 0) {
    $this->time_ms = $time_ms;
  }

  /**
   * @param TL\RpcFunctionReturnResult $function_return_result
   * @return boolean
   */
  public static function functionReturnValue($function_return_result) {
    if ($function_return_result instanceof engine_sleep_result) {
      return $function_return_result->value;
    }
    warning('Unexpected result type in functionReturnValue: ' . ($function_return_result ? get_class($function_return_result) : 'null'));
    return (new engine_sleep_result())->value;
  }

  /**
   * @kphp-inline
   *
   * @param TL\RpcResponse $response
   * @return boolean
   */
  public static function result(TL\RpcResponse $response) {
    return self::functionReturnValue($response->getResult());
  }

  /**
   * @kphp-inline
   *
   * @return \RpcFunctionFetcher
   */
  public function customStore(){
    return null;
  }

  /**
   * @kphp-inline
   *
   * @return \RpcFunctionFetcher
   */
  public function customFetch(){
    return null;
  }

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName() {
    return 'engine.sleep';
  }

}

/**
 * @kphp-tl-class
 */
class engine_sleep_result implements TL\RpcFunctionReturnResult {

  /** @var boolean */
  public $value = false;

}
