<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\engine\Functions;

use VK\TL;

/**
 * @kphp-tl-class
 */
class engine_filteredStat implements TL\RpcFunction {

  /** @var string[] */
  public $stat_names = [];

  /** Allows kphp implicitly load function result class */
  private const RESULT = TL\engine\Functions\engine_filteredStat_result::class;

  /**
   * @param string[] $stat_names
   */
  public function __construct($stat_names = []) {
    $this->stat_names = $stat_names;
  }

  /**
   * @param TL\RpcFunctionReturnResult $function_return_result
   * @return string[]
   */
  public static function functionReturnValue($function_return_result) {
    if ($function_return_result instanceof engine_filteredStat_result) {
      return $function_return_result->value;
    }
    warning('Unexpected result type in functionReturnValue: ' . ($function_return_result ? get_class($function_return_result) : 'null'));
    return (new engine_filteredStat_result())->value;
  }

  /**
   * @kphp-inline
   *
   * @param TL\RpcResponse $response
   * @return string[]
   */
  public static function result(TL\RpcResponse $response) {
    return self::functionReturnValue($response->getResult());
  }

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName() {
    return 'engine.filteredStat';
  }

}

/**
 * @kphp-tl-class
 */
class engine_filteredStat_result implements TL\RpcFunctionReturnResult {

  /** @var string[] */
  public $value = [];

}
