<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\exactlyOnce\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
interface exactlyOnce_PersistentRequest {

  /** Allows kphp implicitly load all available constructors */
  const CONSTRUCTORS = [
    TL\exactlyOnce\Types\exactlyOnce_prepareRequest::class,
    TL\exactlyOnce\Types\exactlyOnce_commitRequest::class
  ];

}
