<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\exactlyOnce\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
class exactlyOnce_prepareRequest implements TL\exactlyOnce\Types\exactlyOnce_PersistentRequest {

  /** @var TL\exactlyOnce\Types\exactlyOnce_uuid */
  public $persistent_query_uuid = null;

  /**
   * @param TL\exactlyOnce\Types\exactlyOnce_uuid $persistent_query_uuid
   */
  public function __construct($persistent_query_uuid = null) {
    $this->persistent_query_uuid = $persistent_query_uuid;
  }

}
