<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\exactlyOnce\Types;

/**
 * @kphp-tl-class
 */
class exactlyOnce_uuid {

  /** @var int */
  public $lo = 0;

  /** @var int */
  public $hi = 0;

  /**
   * @param int $lo
   * @param int $hi
   */
  public function __construct($lo = 0, $hi = 0) {
    $this->lo = $lo;
    $this->hi = $hi;
  }

}
