<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\_common\Functions;

use VK\TL;

/**
 * @kphp-tl-class
 */
class rpcDestActor implements TL\RpcFunction {

  /** @var int */
  public $actor_id = 0;

  /** @var TL\RpcFunction */
  public $query = null;

  /** Allows kphp implicitly load function result class */
  private const RESULT = TL\_common\Functions\rpcDestActor_result::class;

  /**
   * @param int $actor_id
   * @param TL\RpcFunction $query
   */
  public function __construct($actor_id = 0, $query = null) {
    $this->actor_id = $actor_id;
    $this->query = $query;
  }

  /**
   * @param TL\RpcFunctionReturnResult $function_return_result
   * @return TL\RpcFunctionReturnResult
   */
  public static function functionReturnValue($function_return_result) {
    if ($function_return_result instanceof rpcDestActor_result) {
      return $function_return_result->value;
    }
    warning('Unexpected result type in functionReturnValue: ' . ($function_return_result ? get_class($function_return_result) : 'null'));
    return (new rpcDestActor_result())->value;
  }

  /**
   * @kphp-inline
   *
   * @param TL\RpcResponse $response
   * @return TL\RpcFunctionReturnResult
   */
  public static function result(TL\RpcResponse $response) {
    return self::functionReturnValue($response->getResult());
  }

  /**
   * @kphp-inline
   *
   * @return string
   */
  public function getTLFunctionName() {
    return 'rpcDestActor';
  }

}

/**
 * @kphp-tl-class
 */
class rpcDestActor_result implements TL\RpcFunctionReturnResult {

  /** @var TL\RpcFunctionReturnResult */
  public $value = null;

}
