<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\_common\Types;

/**
 * @kphp-tl-class
 */
class boolStat {

  /** @var int */
  public $statTrue = 0;

  /** @var int */
  public $statFalse = 0;

  /** @var int */
  public $statUnknown = 0;

  /**
   * @param int $statTrue
   * @param int $statFalse
   * @param int $statUnknown
   */
  public function __construct($statTrue = 0, $statFalse = 0, $statUnknown = 0) {
    $this->statTrue = $statTrue;
    $this->statFalse = $statFalse;
    $this->statUnknown = $statUnknown;
  }

}
