<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\_common\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
class rpcResponseOk implements TL\RpcResponse {

  /** @var TL\RpcFunctionReturnResult */
  public $result = null;

  /**
   * @param TL\RpcFunctionReturnResult $result
   */
  public function __construct($result = null) {
    $this->result = $result;
  }

  /**
   * @return TL\RpcFunctionReturnResult
   */
  public function getResult() {
    return $this->result;
  }

  /**
   * @return null
   */
  public function getHeader() {
    return null;
  }

  /**
   * @return bool
   */
  public function isError() {
    return false;
  }

  /**
   * @return null
   */
  public function getError() {
    return null;
  }

}
