<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\_common\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
class rpcResponseHeader implements TL\RpcResponse {

  /** @var int */
  public $flags = 0;

  /** @var TL\_common\Types\rpcReqResultExtra */
  public $extra = null;

  /** @var TL\RpcFunctionReturnResult */
  public $result = null;

  /**
   * @param int $flags
   * @param TL\_common\Types\rpcReqResultExtra $extra
   * @param TL\RpcFunctionReturnResult $result
   */
  public function __construct($flags = 0, $extra = null, $result = null) {
    $this->flags = $flags;
    $this->extra = $extra;
    $this->result = $result;
  }

  /**
   * @return TL\RpcFunctionReturnResult
   */
  public function getResult() {
    return $this->result;
  }

  /**
   * @return TL\_common\Types\rpcResponseHeader
   */
  public function getHeader() {
    return $this;
  }

  /**
   * @return bool
   */
  public function isError() {
    return false;
  }

  /**
   * @return null
   */
  public function getError() {
    return null;
  }

}
