<?php

/**
 * AUTOGENERATED, DO NOT EDIT! If you want to modify it, check tl schema.
 *
 * This autogenerated code represents tl class for typed RPC API.
 */

namespace VK\TL\_common\Types;

use VK\TL;

/**
 * @kphp-tl-class
 */
class rpcResponseError implements TL\RpcResponse {

  /** @var int */
  public $error_code = 0;

  /** @var string */
  public $error = '';

  /**
   * @param int $error_code
   * @param string $error
   */
  public function __construct($error_code = 0, $error = '') {
    $this->error_code = $error_code;
    $this->error = $error;
  }

  /**
   * @return null
   */
  public function getResult() {
    return null;
  }

  /**
   * @return null
   */
  public function getHeader() {
    return null;
  }

  /**
   * @return bool
   */
  public function isError() {
    return true;
  }

  /**
   * @return TL\_common\Types\rpcResponseError
   */
  public function getError() {
    return $this;
  }

}
