name: linux-install

on:
  workflow_dispatch:

env:
  kphp_root_dir: /home/kitten/kphp
  kphp_polyfills_dir: /home/kitten/kphp/kphp-polyfills
  kphp_build_dir: /home/kitten/kphp/build

jobs:
  install-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: buster
          - os: focal
          # - os: jammy # TODO: enable after release to artifactory servers

    steps:
    - uses: actions/checkout@v3

    - name: Build and start Docker container
      run: |
        docker build -f $GITHUB_WORKSPACE/.github/workflows/Dockerfile.${{matrix.os}}.install $GITHUB_WORKSPACE -t kphp-build-img-${{matrix.os}}-install
        docker run -dt --name kphp-build-container-${{matrix.os}}-install kphp-build-img-${{matrix.os}}-install

    - name: Run php dummy script
      run: docker exec -u kitten kphp-build-container-${{matrix.os}}-install bash -c 
        "cd ${{env.demo_dir}} && echo 'hello world' > demo.php && kphp --mode=cli --cxx=g++ demo.php && ./kphp_out/cli -o --user kitten"
